config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to:  "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
  end
end
  post 'users/:user_id/posts', to: 'posts#create', as: :user_create_post
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    can :create, [Comment, Post]

    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Comment, author: user
      can :destroy, Post, author: user
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(commentsCounter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_create :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likesCounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  attribute :commentsCounter, default: 0
  attribute :likesCounter, default: 0

  def recent_comments
    comments.last(3)
  end

  validates :title, presence: true, length: { maximum: 250 }
  validates :commentsCounter, numericality: { greater_than_or_equal_to: 0 }
  validates :likesCounter, numericality: { greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  private

  def update_post_counter
    author.update(postsCounter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, dependent: :destroy, foreign_key: :author_id
  has_many :likes, dependent: :destroy, foreign_key: :author_id

  validates :name, presence: true
  validates :postsCounter, numericality: { greater_than_or_equal_to: 0 }

  attribute :postsCounter, default: 0

  def recent_post
    posts.order(created_at: :ASC).limit(3)
  end

  def user_has_liked(post_id)
    likes.exists?(post_id:)
  end

  def remove_user_like(post_id)
    likes.find_by(post_id:).destroy
  end

  def add_user_like(post_id)
    likes.create(post_id:)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :current_user

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new


   end

  def create
    @comment = Comment.new(text: comment_params[:text], post_id: params[:post_id], author_id: current_user[:id])

    if @comment.save
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id]),
                  notice: 'Comment added successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
    @comment = Comment.find(params[:id])
  
    authorize! :destroy, @comment
  
    if @comment.destroy
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully deleted.'
    else
      redirect_to user_post_path(@user, @post), alert: 'Failed to delete comment.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: %i[create destroy]

  def create
    @like = @post.likes.build(author: current_user)
    if @like.save
      redirect_to user_post_path(user_id: current_user.id, id: @post.id), notice: 'Post liked!'
    else
      redirect_to user_post_path(user_id: current_user.id, id: @post.id), alert: 'Sorry, there was an error.'
    end
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    @like.destroy
    redirect_to user_post_path(user_id: current_user.id, id: @post.id), notice: 'Post unliked!'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User..includes(:posts, :comments).find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'Post not found'
    redirect_to user_posts_path(@user)
  end
  
  
  def new
    @post = current_user.posts.new

  end

  def create
    @post = Post.new(title: post_params[:title], text: post_params[:text], author_id: current_user[:id],
                     commentsCounter: 0, likesCounter: 0)

    if @post.save
      redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy
    redirect_to user_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, only: [:index]
  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<section id="add-post-form" class="w-[80%] mx-auto">
    <h1 class="text-3xl font-bold">Add Comment</h1>

 <%= form_with(model: @comment, url: user_post_comments_path, method: :post, class: 'mt-5 w-[70%] mx-auto') do |form|%>
    <div class="field">
        <%= form.label :text, 'Comment'%>
        <%= form.text_area :text, placeholder: 'Share your thoughts...' %>
        <% if form.object.errors.any? %>
            <span class="block error">
                <%= render_error_message_for_input(form, :text) %>
            </span>
        <% end %>
    </div>
    
    <div class="field">
        <%= form.submit 'Add Comment', class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-5 px-4 rounded' %>
    </div>
 <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AIUpdate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<main>
    <div id="list_item" class="list_item">
        <div class="photo">
          <% if @user && @user.photo %>
  <%= image_tag(@user.photo) %>
<% end %>
        </div>
        <div class="user_name">
           <h4><%= @user.name %></h4>
           <p>Number of posts: <%= @user.posts.count %></p>
        </div>
    </div>
    <% if @user.posts.blank? %>
    <p>There are not any post currently for this author.</p>
    <% else %>
        <ul id="list" class="list">
        <% @posts.includes({comments: [:author]}, :likes).each do |post| %>
        <li class="post">
            <a class="link" href="/users/<%= @user.id %>/posts/<%= post.id %>">
                <div class="text">
                    <h4>Post #<%= post.id %></h4> <br/>
                    <h2><%=post.title%></h2>
                    <p><%= truncate(post.text, length: 20) %></p>
                    <p class="float">Comments:<%= post.commentsCounter %>, Likes: <%= post.likes.count %></p>
                </div>
            </a>
            <div class="comments">
                <div class="comments_list">
                    <ul>
                        <% post.recent_comments.each do |comment| %>
                        <li><%= @user.name %>: <%= comment.text %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </li>
        <% end %>
        </ul>
    <% end %>
    <div class="btn_container">
      <button id="next" class="see_more">Next</button>
    </div>
</main>

app/views/posts/new.html.erb
<section id="add-post-form" class="w-[80%] mx-auto">
    <div class="flex items-center justify-between">
    <h1 class="text-3xl font-bold">New Post</h1>
</div>


 <%= form_with(model: @post, url: user_create_post_path, method: :post, remote: false,  class: 'mt-5 w-[70%] mx-auto') do |form|%>

    <div class="field">
        <%= form.label :title, 'Post title'%>
        <%= form.text_field :title %>
        <% if form.object.errors.any? %>
            <span class="block error">
                <%= render_error_message_for_input(form, :title) %>
            </span>
        <% end %>

    </div>
    <div class="field">
        <%= form.label :text, 'Post Content'%>
        <%= form.text_area :text %>
        <% if form.object.errors.any? %>
            <span class="block error">
                <%= render_error_message_for_input(form, :text) %>
            </span>
        <% end %>
    </div>
    
    <div class="field">
        <%= form.submit 'Create Post', class: 'bg-green-500 hover:bg-green-700 text-white font-bold py-5 px-4 rounded' %>
    </div>
 <% end %>
</section>

app/views/posts/show.html.erb
<main>
    <div class="detail">
        <div class="user">
       <h1><%=@post.title%></h1> 
            <h4>Post #<%= @post.id %> by <%= @post.author.name %></h4>
            <p>Comments:<%= @post.comments.count %>, Likes: <%= @post.likes.count %></p>
        </div><br/>
        <div class="detail_text">
            <%= @post.text %>
        </div>
    </div>
    <ul class="detail_comments">
        <% @post.comments.each do |comment| %>
         <li><%= @post.author.name%>: <%= comment.text%>
        
              <% if can? :destroy, comment %>
                 <%= button_to "Delete Comment", user_post_comment_path(@user, @post, comment), method: :delete %>
              <% end %>
          </li>
        <% end %>
             
  </ul>
    <div class="btn_container">
    
      <% if current_user.likes.exists?(post: @post) %>
      <%= button_to user_post_like_path(user_id: @user.id, post_id: @post.id, id: current_user.likes.find_by(post: @post).id), method: :delete, class: "like-btn" do %>
        Like<%= @post.likes.count %>
      <% end %>
    <% else %>
      <%= button_to user_post_likes_path(user_id: current_user.id, post_id: @post.id), method: :post, class: "like-btn" do %>
        Like<%= @post.likes.count %>
      <% end %>
    <% end %>
  </div>

 <div class="button_holder">
      <button class="create_post_btn">
          <%= link_to 'Create new comment', new_user_post_comment_path(post_id: @post.id) %>
      </button>
    </div>




<% if can? :destroy, @post %>
  <%= button_to "Delete Post", user_post_path(@user, @post), method: :delete %>
<% end %>


</main>

app/views/users/index.html.erb
<% if @users.blank? %>
  <p>There are not any users currently in the system.</p>
<% else %>
  <h1>All users</h1>
  <main>
    <ul class="users_list">
      <% @users.each do |user| %>
        
          <li class="list_item">
          
          <a class="link" href="/users/<%= user.id %>">
          
            <div class="photo">
             <% if user && user.photo %>
  <%= image_tag(user.photo) %>
<% end %>
            </div>
            <div class="user_name">
              <h3><%= user.name %></h3>
              <p>Number of posts: <%= user.postsCounter %></p>
            </div>
            </a>
          </li>
        
      <% end %>
    </ul>
    

     
  </main>
<% end %>

app/views/users/show.html.erb
<main>
    <div class="list_item">
        <div class="photo">
           <% if @user && @user.photo %>
  <%= image_tag(@user.photo) %>
<% end %>
        </div>
        <div class="user_name">
            <h3><%= @user.name %></h3>
            <p>Number of posts: <%= @user.postsCounter %></p>
        </div>
    </div>
    <div class="bio">
        <h4>Bio</h4> <br/>
        <p><%= @user.bio%></p>
    </div>
    <ul class="list">
        <% @user.recent_post.each do |post|%>
        <a href="/users/<%=@user.id%>/posts/<%= post.id %>">
            <li class="text">
                <h4>Post #<%= post.id %></h4><br/>
                <p><%= post.text %></p>
                <p class="float">Comments:<%= post.comments.count %>, Likes: <%= post.likes.count %></p>
            </li>
        </a>
        <% end %>
    </ul>
    <div class="btn_container">

       <a href="/users/<%=@user.id%>/posts" >
           See all posts
        </a>
        
    </div>
     <div class="button_holder">
      <button class="create_post_btn">
          <%= link_to 'Create new post', new_user_post_path(user_id: @current_user.id) %>
      </button>
    </div>
</main>